version: '3.9'
services:
  app:
    container_name: marvel
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_host

  postgres_host:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres