DROP TABLE IF EXISTS characters_comics;
DROP TABLE IF EXISTS comics;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS images;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq START WITH 100000;


CREATE TABLE images
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    path VARCHAR(255)
);

CREATE TABLE characters
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_id    INTEGER
        CONSTRAINT characters_images_id_fk REFERENCES images
);

CREATE TABLE comics
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_id    INTEGER
        CONSTRAINT comics_images_id_fk REFERENCES images
);

CREATE TABLE characters_comics
(
    character_id INTEGER
        CONSTRAINT characters_comics_characters_id_fk REFERENCES characters,
    comic_id     INTEGER
        CONSTRAINT characters_comics_comics_id_fk REFERENCES comics
);

