/*
 * This file is generated by jOOQ.
 */
package com.ivanzap.marvel.domain.tables.records;


import com.ivanzap.marvel.domain.tables.Characters;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharactersRecord extends UpdatableRecordImpl<CharactersRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.characters.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.characters.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.characters.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.characters.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.characters.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.characters.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Characters.CHARACTERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Characters.CHARACTERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Characters.CHARACTERS.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public CharactersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CharactersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CharactersRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CharactersRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharactersRecord
     */
    public CharactersRecord() {
        super(Characters.CHARACTERS);
    }

    /**
     * Create a detached, initialised CharactersRecord
     */
    public CharactersRecord(Integer id, String name, String description) {
        super(Characters.CHARACTERS);

        setId(id);
        setName(name);
        setDescription(description);
    }
}
