/*
 * This file is generated by jOOQ.
 */
package com.ivanzap.marvel.domain.tables.records;


import com.ivanzap.marvel.domain.tables.CharactersComics;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharactersComicsRecord extends TableRecordImpl<CharactersComicsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.characters_comics.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.characters_comics.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.characters_comics.comic_id</code>.
     */
    public void setComicId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.characters_comics.comic_id</code>.
     */
    public Integer getComicId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CharactersComics.CHARACTERS_COMICS.CHARACTER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CharactersComics.CHARACTERS_COMICS.COMIC_ID;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public Integer component2() {
        return getComicId();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public Integer value2() {
        return getComicId();
    }

    @Override
    public CharactersComicsRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public CharactersComicsRecord value2(Integer value) {
        setComicId(value);
        return this;
    }

    @Override
    public CharactersComicsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharactersComicsRecord
     */
    public CharactersComicsRecord() {
        super(CharactersComics.CHARACTERS_COMICS);
    }

    /**
     * Create a detached, initialised CharactersComicsRecord
     */
    public CharactersComicsRecord(Integer characterId, Integer comicId) {
        super(CharactersComics.CHARACTERS_COMICS);

        setCharacterId(characterId);
        setComicId(comicId);
    }
}
