/*
 * This file is generated by jOOQ.
 */
package com.ivanzap.marvel.domain.tables.records;


import com.ivanzap.marvel.domain.tables.Comics;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComicsRecord extends UpdatableRecordImpl<ComicsRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.comics.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.comics.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.comics.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.comics.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.comics.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.comics.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Comics.COMICS.ID;
    }

    @Override
    public Field<String> field2() {
        return Comics.COMICS.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Comics.COMICS.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public ComicsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ComicsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ComicsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ComicsRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComicsRecord
     */
    public ComicsRecord() {
        super(Comics.COMICS);
    }

    /**
     * Create a detached, initialised ComicsRecord
     */
    public ComicsRecord(Integer id, String title, String description) {
        super(Comics.COMICS);

        setId(id);
        setTitle(title);
        setDescription(description);
    }
}
