/*
 * This file is generated by jOOQ.
 */
package com.ivanzap.marvel.domain;


import com.ivanzap.marvel.domain.tables.Characters;
import com.ivanzap.marvel.domain.tables.CharactersComics;
import com.ivanzap.marvel.domain.tables.Comics;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.characters</code>.
     */
    public final Characters CHARACTERS = Characters.CHARACTERS;

    /**
     * The table <code>public.characters_comics</code>.
     */
    public final CharactersComics CHARACTERS_COMICS = CharactersComics.CHARACTERS_COMICS;

    /**
     * The table <code>public.comics</code>.
     */
    public final Comics COMICS = Comics.COMICS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Characters.CHARACTERS,
            CharactersComics.CHARACTERS_COMICS,
            Comics.COMICS);
    }
}
