/*
 * This file is generated by jOOQ.
 */
package com.ivanzap.marvel.domain;


import com.ivanzap.marvel.domain.tables.Characters;
import com.ivanzap.marvel.domain.tables.CharactersComics;
import com.ivanzap.marvel.domain.tables.Comics;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.characters</code>.
     */
    public static final Characters CHARACTERS = Characters.CHARACTERS;

    /**
     * The table <code>public.characters_comics</code>.
     */
    public static final CharactersComics CHARACTERS_COMICS = CharactersComics.CHARACTERS_COMICS;

    /**
     * The table <code>public.comics</code>.
     */
    public static final Comics COMICS = Comics.COMICS;
}
